name: buildkit
"on":
  push:
    paths:
    - build/buildkit/Dockerfile.buildkit
    - build/buildkit/Dockerfile.version
jobs:
  buildkit:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Versioned Build
      if: github.ref == 'refs/heads/master'
      run: cd build/buildkit && make build HUB=querycap NAME=buildkit
    - name: Temp Build
      if: github.ref != 'refs/heads/master'
      run: cd build/buildkit && make build HUB=querycap NAME=buildkit TAG=temp-${{ github.sha }}
