name: docker-buildx
"on":
  push:
    paths:
    - build/docker-buildx/**
jobs:
  docker-buildx:
    runs-on:
    - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - name: Versioned Build
      if: github.ref == 'refs/heads/master'
      run: cd build/docker-buildx && make build HUB=querycap NAME=docker-buildx
    - name: Temp Build
      if: github.ref != 'refs/heads/master'
      run: cd build/docker-buildx && make build HUB=querycap NAME=docker-buildx TAG=${{ github.sha }}
