name: docker-buildx

on:
  push:
    paths:
      - '.github/workflows/docker-buildx.yml'
      - 'docker-buildx/**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@master
      - uses: docker/setup-buildx-action@master
      - name: setup buildx
        run: |
          cat > ~/.docker/config.json << EOF
          ${{ secrets.DOCKER_CONFIG }}
          EOF
      - run: cd docker-buildx && make build
      - run: cd docker-buildx && make sync