name: zz-sync-gitlab-runner-helper
"on":
  push:
    paths:
    - sync/Dockerfile.gitlab-runner-helper,arm64
jobs:
  sync:
    runs-on:
    - self-hosted
    - arm64
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_MIRROR_PASSWORD }}
        registry: ${{ secrets.DOCKER_MIRROR_REGISTRY }}
        username: ${{ secrets.DOCKER_MIRROR_USERNAME }}
    - run: cd sync && make sync HUB=${{ secrets.DOCKER_MIRROR_REGISTRY }} NAME=gitlab-runner-helper,arm64
